sudo: required
language: bash
services:
  - docker

env:
  matrix:
    - VARIANT=php5.6/apache
      BRANCH=stable

    - VARIANT=php5.6/fpm
      BRANCH=stable

    - VARIANT=php7.0/apache
      BRANCH=stable
    - VARIANT=php7.0/apache
      BRANCH=edge

    - VARIANT=php7.0/fpm
      BRANCH=stable
    - VARIANT=php7.0/fpm
      BRANCH=edge

    - VARIANT=php7.1/apache
      BRANCH=stable
    - VARIANT=php7.1/apache
      BRANCH=edge

    - VARIANT=php7.1/fpm
      BRANCH=stable
    - VARIANT=php7.1/fpm
      BRANCH=edge

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - docker -v
  - env | sort
  - source version
  - if [ "$BRANCH" == "stable" ]; then build="build.$OCTOBERCMS_BUILD"; else build="build.$OCTOBERCMS_EDGE_BUILD"; fi
  - echo $build
  - if [ "$BRANCH" == "stable" ]; then prefix=""; else prefix="$BRANCH-"; fi
  - image='aspendigital/octobercms'; slash='/'; tag="$prefix${VARIANT//$slash/-}";
  - if [ "$BRANCH" == "edge" ]; then dockerfile="Dockerfile.edge"; else dockerfile="Dockerfile"; fi
  - cd "$VARIANT"

script:
  - docker build -t "$image:$tag" -f $dockerfile .
  - ~/official-images/test/run.sh "$image:$tag"
  - docker run --rm "$image:$tag" vendor/bin/phpunit

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      docker push "$image:$tag";

      docker build -t "$image:$build-${VARIANT//$slash/-}" -f $dockerfile .;
      docker push "$image:$build-${VARIANT//$slash/-}";

      if [ "$VARIANT" == "php7.1/apache" ]; then
        docker build -t "$image:$build" -f $dockerfile .;
        docker push "$image:$build";

        if [ "$BRANCH" == "stable" ]; then
          docker build -t "$image:latest" -f $dockerfile .;
          docker push "$image:latest";
        else
          docker build -t "$image:edge" -f $dockerfile .;
          docker push "$image:edge";
        fi
      fi

    fi;
  - docker images;
